<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_protect_site"
 *
 * Auto generated by Extension Builder 2019-12-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Protect site',
    'description' => 'This extnesion make secure your pages with password',
    'category' => 'plugin',
    'author' => 'sanjay@nitsan.in',
    'author_company' => 'NITSAN Technologies Pvt Ltd',
    'author_email' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.0.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
